name: Notimpo
description: 'Sends Important Developer Notifications, can be used in Github Actions'
author: 'Shaiju t'
inputs:
  first-name:
    required: true
    description: 'Your first name'
branding:
  icon: 'power'
  color: 'green'
runs:
  using: 'node12'
  main: 'dist/index.js'